//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecomprojak.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecomadoEntities : DbContext
    {
        public ecomadoEntities()
            : base("name=ecomadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Tbl_Category> Tbl_Category { get; set; }
        public DbSet<Tbl_Contact> Tbl_Contact { get; set; }
        public DbSet<Tbl_Login> Tbl_Login { get; set; }
        public DbSet<Tbl_Order> Tbl_Order { get; set; }
        public DbSet<Tbl_Product> Tbl_Product { get; set; }
        public DbSet<Tbl_Register> Tbl_Register { get; set; }
    }
}
