//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecomprojak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        public int Ordno { get; set; }
        public int OrdId { get; set; }
        public string Uemail { get; set; }
        public int pid { get; set; }
        public string pname { get; set; }
        public string pcate { get; set; }
        public string price { get; set; }
        public string disprice { get; set; }
        public string pquantity { get; set; }
        public string ppic { get; set; }
        public string orddate { get; set; }
    }
}
