//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecomprojak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Contact
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string enquiry { get; set; }
        public string regdate { get; set; }
    }
}
